export const LOCATIONS = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;

export type LocationName = (typeof LOCATIONS)[number];

export const PRODUCT_CATEGORIES = [
  "Cars",
  "Property",
  "Electronics",
  "Phones & Tablets",
  "Fashion",
  "Home & Furniture",
  "Pets",
  "Services",
  "Jobs",
  "Vehicle Parts",
  "Agricultural Products",
  "Beauty & Personal Care",
  "Babies & Kids",
  "Leisure & Activities",
  "Commercial Equipment",
  "Other",
] as const;

export type ProductCategory = (typeof PRODUCT_CATEGORIES)[number];

export interface Product {
  id: string;
  name: string;
  price: number;
  seller: string;
  rating: number;
  image: string;
  fallback: string;
  location: LocationName;
  category: ProductCategory;
  condition: "New" | "Fairly Used" | "Second-hand" | "Made to Order";
  promoted: boolean;
  description: string;
  specs: Record<string, string>;
  listedAt: number;
}

const ASSET = {
  car: "/products/used-sedan.jpg",
  phone: "/products/smartphone.jpg",
  sofa: "/products/sofa.jpg",
  sneaker: "/products/sneakers.jpg",
  power: "/products/solar-generator.jpg",
} as const;

const productNames: Array<{
  name: string;
  price: number;
  seller: string;
  location: LocationName;
  category: ProductCategory;
  image: keyof typeof ASSET;
  fallback: string;
  condition: Product["condition"];
  description: string;
  specs: Record<string, string>;
}> = [
  {
    name: "2018 Executive Sedan",
    price: 8450000,
    seller: "Prime Auto Lagos",
    location: "Lagos",
    category: "Cars",
    image: "car",
    fallback: "🚗",
    condition: "Fairly Used",
    description: "Neat executive sedan with clean interior, AC and complete papers.",
    specs: { Year: "2018", Transmission: "Automatic", Fuel: "Petrol", Color: "Silver" },
  },
  {
    name: "128GB Pro Smartphone",
    price: 425000,
    seller: "TechHub NG",
    location: "FCT Abuja",
    category: "Phones & Tablets",
    image: "phone",
    fallback: "📱",
    condition: "New",
    description: "Factory-sealed smartphone with fast charger and one-year shop warranty.",
    specs: { Storage: "128GB", RAM: "8GB", Condition: "New", Color: "Black" },
  },
  {
    name: "Modern 3-Seater Sofa",
    price: 285000,
    seller: "HomeStyle Furniture",
    location: "Oyo",
    category: "Home & Furniture",
    image: "sofa",
    fallback: "🛋️",
    condition: "New",
    description: "Comfortable three-seater sofa with durable fabric and sturdy hardwood legs.",
    specs: { Material: "Fabric", Seats: "3", Color: "Navy blue", Delivery: "Available" },
  },
  {
    name: "Portable Solar Power Station",
    price: 315000,
    seller: "BrightGrid Energy",
    location: "Rivers",
    category: "Commercial Equipment",
    image: "power",
    fallback: "🔋",
    condition: "New",
    description: "Portable solar generator set with folding panel and essential charging cables.",
    specs: { Capacity: "1200Wh", Output: "1500W", Panel: "200W", Warranty: "12 months" },
  },
  {
    name: "Classic Everyday Sneakers",
    price: 48000,
    seller: "Streetline Fashion",
    location: "Kano",
    category: "Fashion",
    image: "sneaker",
    fallback: "👟",
    condition: "New",
    description: "Comfortable lightweight sneakers for daily wear. Multiple sizes available.",
    specs: { Sizes: "40–45", Material: "Mesh & rubber", Color: "White / green", Gender: "Unisex" },
  },
  {
    name: "2020 Compact Sedan",
    price: 10600000,
    seller: "AutoChoice Abuja",
    location: "FCT Abuja",
    category: "Cars",
    image: "car",
    fallback: "🚙",
    condition: "Fairly Used",
    description: "Well-maintained compact sedan, reverse camera and service history included.",
    specs: { Year: "2020", Transmission: "Automatic", Mileage: "62,000 km", Color: "Silver" },
  },
  {
    name: "256GB Android Phone",
    price: 365000,
    seller: "Mobile World",
    location: "Kaduna",
    category: "Phones & Tablets",
    image: "phone",
    fallback: "📲",
    condition: "New",
    description: "Large-screen Android phone with long battery life and premium camera system.",
    specs: { Storage: "256GB", RAM: "12GB", Screen: "6.7 inch", Color: "Graphite" },
  },
  {
    name: "L-Shaped Living Room Sofa",
    price: 410000,
    seller: "Comfort House",
    location: "Lagos",
    category: "Home & Furniture",
    image: "sofa",
    fallback: "🛋️",
    condition: "Made to Order",
    description:
      "Custom-made L-shaped sofa, made to your preferred fabric colour within seven days.",
    specs: { Material: "Premium fabric", Seats: "5", "Lead time": "7 days", Warranty: "6 months" },
  },
  {
    name: "Leather Office Sneakers",
    price: 55000,
    seller: "Mode & More",
    location: "Enugu",
    category: "Fashion",
    image: "sneaker",
    fallback: "👟",
    condition: "New",
    description: "Smart casual sneakers with soft lining for office or weekend use.",
    specs: { Sizes: "41–46", Material: "Leather blend", Color: "White", Gender: "Men" },
  },
  {
    name: "Solar Backup Kit 1.5kVA",
    price: 470000,
    seller: "Power Solutions NG",
    location: "Ogun",
    category: "Commercial Equipment",
    image: "power",
    fallback: "☀️",
    condition: "New",
    description:
      "Home and small-shop solar backup kit with inverter, batteries and installation guide.",
    specs: {
      Inverter: "1.5kVA",
      Battery: "2 units",
      "Solar panel": "400W",
      Installation: "Available",
    },
  },
  {
    name: "2017 Family Sedan",
    price: 7200000,
    seller: "Kano Motors",
    location: "Kano",
    category: "Cars",
    image: "car",
    fallback: "🚘",
    condition: "Second-hand",
    description: "Reliable family sedan with sound engine, tidy body and working air conditioning.",
    specs: { Year: "2017", Transmission: "Automatic", Fuel: "Petrol", Color: "Grey" },
  },
  {
    name: "Wireless Work Phone",
    price: 230000,
    seller: "Gadget Centre",
    location: "Akwa Ibom",
    category: "Electronics",
    image: "phone",
    fallback: "📱",
    condition: "Fairly Used",
    description: "Carefully used premium phone, tested and ready for a new owner.",
    specs: { Storage: "128GB", Battery: "90%", Network: "5G", Color: "Black" },
  },
  {
    name: "Minimalist Lounge Sofa",
    price: 235000,
    seller: "Deco Home",
    location: "Edo",
    category: "Home & Furniture",
    image: "sofa",
    fallback: "🪑",
    condition: "New",
    description: "Compact sofa set for a lounge, apartment or reception area.",
    specs: { Material: "Fabric", Seats: "3", Color: "Blue", Delivery: "Nationwide" },
  },
  {
    name: "Outdoor Trail Sneakers",
    price: 62000,
    seller: "Active Life NG",
    location: "Plateau",
    category: "Leisure & Activities",
    image: "sneaker",
    fallback: "🥾",
    condition: "New",
    description: "Durable trail sneakers with cushioned sole for walking and light hiking.",
    specs: { Sizes: "39–45", Sole: "Non-slip", Color: "White / green", Use: "Outdoor" },
  },
  {
    name: "Business Solar Starter Pack",
    price: 690000,
    seller: "SunWorks Africa",
    location: "Anambra",
    category: "Commercial Equipment",
    image: "power",
    fallback: "🔌",
    condition: "New",
    description: "Solar power bundle designed for POS shops, offices and small businesses.",
    specs: { Output: "2.2kW", Battery: "LiFePO4", Panel: "600W", Support: "Installation" },
  },
  {
    name: "2019 City Sedan",
    price: 9300000,
    seller: "MetroDrive",
    location: "Rivers",
    category: "Cars",
    image: "car",
    fallback: "🚗",
    condition: "Fairly Used",
    description: "City sedan with very clean body, responsive steering and complete registration.",
    specs: { Year: "2019", Transmission: "Automatic", Mileage: "71,000 km", Color: "Silver" },
  },
  {
    name: "Tablet for Study & Work",
    price: 195000,
    seller: "Campus Tech",
    location: "Kwara",
    category: "Phones & Tablets",
    image: "phone",
    fallback: "📟",
    condition: "New",
    description: "Slim tablet suitable for virtual classes, note-taking and video calls.",
    specs: { Storage: "128GB", Screen: "11 inch", Network: "Wi-Fi", Color: "Black" },
  },
  {
    name: "Premium Couch Set",
    price: 525000,
    seller: "Ikeja Interiors",
    location: "Lagos",
    category: "Home & Furniture",
    image: "sofa",
    fallback: "🛋️",
    condition: "New",
    description: "Premium lounge couch set built with resilient foam and easy-clean upholstery.",
    specs: { Pieces: "3", Material: "Fabric", Color: "Blue", Warranty: "1 year" },
  },
  {
    name: "Sports Sneakers Pair",
    price: 39000,
    seller: "Fresh Kicks",
    location: "Benue",
    category: "Fashion",
    image: "sneaker",
    fallback: "👟",
    condition: "New",
    description: "Everyday sports sneakers with breathable upper and flexible sole.",
    specs: { Sizes: "38–44", Material: "Mesh", Color: "White / green", Gender: "Unisex" },
  },
  {
    name: "Mobile Power Kit",
    price: 255000,
    seller: "EcoVolt",
    location: "Nasarawa",
    category: "Electronics",
    image: "power",
    fallback: "🔋",
    condition: "New",
    description: "Compact portable power kit for laptops, lights and basic devices.",
    specs: { Capacity: "700Wh", Output: "800W", Recharge: "Solar / AC", Weight: "9kg" },
  },
  {
    name: "2016 Sedan, Clean Title",
    price: 6350000,
    seller: "DriveRight",
    location: "Delta",
    category: "Cars",
    image: "car",
    fallback: "🚙",
    condition: "Second-hand",
    description: "Clean title sedan with recent servicing and ready-to-drive condition.",
    specs: { Year: "2016", Transmission: "Automatic", Fuel: "Petrol", Color: "Silver" },
  },
  {
    name: "Camera Phone, 256GB",
    price: 340000,
    seller: "Digital Depot",
    location: "Cross River",
    category: "Electronics",
    image: "phone",
    fallback: "📱",
    condition: "New",
    description: "Fast, dependable camera phone with ample storage and fast charging.",
    specs: { Storage: "256GB", Camera: "50MP", Network: "5G", Color: "Black" },
  },
  {
    name: "Three-Seat Reception Sofa",
    price: 270000,
    seller: "Office Craft",
    location: "FCT Abuja",
    category: "Commercial Equipment",
    image: "sofa",
    fallback: "🛋️",
    condition: "New",
    description: "Professional reception sofa for offices, clinics and salons.",
    specs: { Seats: "3", Material: "Fabric", Colour: "Blue", Use: "Commercial" },
  },
  {
    name: "Training Sneakers",
    price: 45000,
    seller: "Fit Store",
    location: "Osun",
    category: "Fashion",
    image: "sneaker",
    fallback: "👟",
    condition: "New",
    description: "Supportive training footwear with light construction and secure grip.",
    specs: { Sizes: "40–45", Use: "Gym / casual", Color: "White / green", Sole: "Rubber" },
  },
  {
    name: "Home Solar Essentials",
    price: 385000,
    seller: "Green Current",
    location: "Ekiti",
    category: "Home & Furniture",
    image: "power",
    fallback: "☀️",
    condition: "New",
    description: "Solar essentials for lights, TV, fan and mobile-device charging.",
    specs: { Output: "1kW", Battery: "100Ah", Panels: "2", Warranty: "12 months" },
  },
  {
    name: "Smart Sedan 2018",
    price: 8100000,
    seller: "Ace Autos",
    location: "Oyo",
    category: "Cars",
    image: "car",
    fallback: "🚗",
    condition: "Fairly Used",
    description: "Low-maintenance sedan with clean upholstery and working navigation display.",
    specs: { Year: "2018", Transmission: "Automatic", Mileage: "78,000 km", Color: "Silver" },
  },
  {
    name: "Work & Play Smartphone",
    price: 285000,
    seller: "Phone Plug",
    location: "Katsina",
    category: "Phones & Tablets",
    image: "phone",
    fallback: "📲",
    condition: "New",
    description: "All-day battery smartphone for work, gaming and social media.",
    specs: { Storage: "128GB", Battery: "5000mAh", Network: "4G", Color: "Black" },
  },
  {
    name: "Apartment Sofa Set",
    price: 330000,
    seller: "Urban Living",
    location: "Imo",
    category: "Home & Furniture",
    image: "sofa",
    fallback: "🪑",
    condition: "Fairly Used",
    description: "Very neat apartment sofa with washable covers and strong frame.",
    specs: { Pieces: "3", Condition: "Neat", Color: "Blue", Pickup: "Available" },
  },
  {
    name: "Streetwear Sneakers",
    price: 58000,
    seller: "Urban Closet",
    location: "Bayelsa",
    category: "Fashion",
    image: "sneaker",
    fallback: "👟",
    condition: "New",
    description: "Streetwear sneakers with clean silhouette and all-day comfort.",
    specs: { Sizes: "40–46", Material: "Suede blend", Color: "White / green", Gender: "Unisex" },
  },
  {
    name: "Solar Cart for Vendors",
    price: 445000,
    seller: "Market Power",
    location: "Bauchi",
    category: "Commercial Equipment",
    image: "power",
    fallback: "🔌",
    condition: "New",
    description: "Portable solar unit for vendors, small shops and mobile businesses.",
    specs: { Output: "1.2kW", Battery: "Lithium", Panel: "Foldable", Delivery: "Available" },
  },
  {
    name: "2015 Reliable Sedan",
    price: 5450000,
    seller: "SureDeal Motors",
    location: "Kogi",
    category: "Cars",
    image: "car",
    fallback: "🚘",
    condition: "Second-hand",
    description: "Reliable daily-driver sedan, recently serviced and ready for inspection.",
    specs: { Year: "2015", Transmission: "Automatic", Fuel: "Petrol", Color: "Silver" },
  },
  {
    name: "Premium Phone Bundle",
    price: 475000,
    seller: "City Gadgets",
    location: "Sokoto",
    category: "Phones & Tablets",
    image: "phone",
    fallback: "📱",
    condition: "New",
    description: "Premium phone bundle including charger, case and screen protector.",
    specs: { Storage: "256GB", RAM: "12GB", Network: "5G", Color: "Black" },
  },
  {
    name: "Compact Living Sofa",
    price: 210000,
    seller: "Space Savers",
    location: "Niger",
    category: "Home & Furniture",
    image: "sofa",
    fallback: "🛋️",
    condition: "New",
    description: "Space-saving three-seat sofa for modern homes and apartments.",
    specs: { Seats: "3", Width: "210cm", Color: "Blue", Delivery: "Available" },
  },
  {
    name: "Comfort Run Sneakers",
    price: 52000,
    seller: "Run Club Store",
    location: "Taraba",
    category: "Leisure & Activities",
    image: "sneaker",
    fallback: "👟",
    condition: "New",
    description: "Cushioned running sneakers for daily exercise and casual use.",
    specs: { Sizes: "39–45", Use: "Running", Colour: "White / green", Sole: "Cushioned" },
  },
  {
    name: "Off-Grid Power Box",
    price: 780000,
    seller: "VoltCraft",
    location: "Borno",
    category: "Commercial Equipment",
    image: "power",
    fallback: "⚡",
    condition: "New",
    description: "High-capacity power box for homes and independent workspaces.",
    specs: { Output: "3kW", Battery: "2.5kWh", Panels: "800W", Warranty: "18 months" },
  },
  {
    name: "2019 Executive Car",
    price: 11250000,
    seller: "Premium Wheels",
    location: "Edo",
    category: "Cars",
    image: "car",
    fallback: "🚗",
    condition: "Fairly Used",
    description: "Executive sedan with refined interior and very clean exterior.",
    specs: { Year: "2019", Transmission: "Automatic", Mileage: "55,000 km", Color: "Silver" },
  },
  {
    name: "Pro Camera Smartphone",
    price: 510000,
    seller: "Vision Mobile",
    location: "Zamfara",
    category: "Phones & Tablets",
    image: "phone",
    fallback: "📸",
    condition: "New",
    description: "Premium camera smartphone for creators and business users.",
    specs: { Storage: "256GB", Camera: "Triple lens", Network: "5G", Color: "Black" },
  },
  {
    name: "Family Room Sofa",
    price: 360000,
    seller: "Northern Interiors",
    location: "Jigawa",
    category: "Home & Furniture",
    image: "sofa",
    fallback: "🛋️",
    condition: "New",
    description: "Comfortable sofa for a relaxed family room, built for daily use.",
    specs: { Seats: "3", Material: "Fabric", Color: "Navy", Warranty: "6 months" },
  },
  {
    name: "Daily Walk Sneakers",
    price: 35000,
    seller: "Everyday Fit",
    location: "Yobe",
    category: "Fashion",
    image: "sneaker",
    fallback: "👟",
    condition: "New",
    description: "Lightweight sneakers designed for commuting, walking and daily errands.",
    specs: { Sizes: "40–45", Use: "Daily", Color: "White / green", Gender: "Unisex" },
  },
  {
    name: "Solar Business Backup",
    price: 950000,
    seller: "Reliable Energy",
    location: "Adamawa",
    category: "Commercial Equipment",
    image: "power",
    fallback: "🔋",
    condition: "New",
    description: "Serious solar backup solution for business operations and reliable uptime.",
    specs: { Output: "3.5kW", Battery: "5kWh", Panels: "1kW", Installation: "Included" },
  },
];

export const products: Product[] = productNames.map((product, index) => ({
  ...product,
  id: String(index + 1),
  image: ASSET[product.image],
  rating: Number((4.1 + ((index * 3) % 9) / 10).toFixed(1)),
  promoted: index < 3 || index % 11 === 0,
  listedAt: Date.now() - index * 86_400_000,
}));

export const jobs = [
  {
    id: "1",
    title: "Customer Support Officer",
    company: "Prime Services",
    location: "Lagos",
    salary: "₦250k/mo",
    type: "Full-time",
    promoted: true,
  },
  {
    id: "2",
    title: "Sales Representative",
    company: "MarketReach",
    location: "FCT Abuja",
    salary: "₦180k/mo",
    type: "Contract",
    promoted: false,
  },
  {
    id: "3",
    title: "Warehouse Supervisor",
    company: "SupplyHub",
    location: "Kaduna",
    salary: "₦220k/mo",
    type: "Full-time",
    promoted: false,
  },
  {
    id: "4",
    title: "Digital Marketing Associate",
    company: "Growth Lane",
    location: "Lagos",
    salary: "₦200k/mo",
    type: "Remote",
    promoted: false,
  },
  {
    id: "5",
    title: "Retail Store Manager",
    company: "HomeStyle",
    location: "Kano",
    salary: "₦190k/mo",
    type: "Full-time",
    promoted: true,
  },
] as const;

export const tutorials = [
  {
    id: "1",
    title: "How to create a trusted listing",
    duration: "12 min",
    level: "Beginner",
    icon: "🧾",
  },
  {
    id: "2",
    title: "Taking photos that sell",
    duration: "18 min",
    level: "Intermediate",
    icon: "📸",
  },
  {
    id: "3",
    title: "Safe marketplace conversations",
    duration: "9 min",
    level: "Beginner",
    icon: "💬",
  },
  {
    id: "4",
    title: "Packaging and delivery basics",
    duration: "15 min",
    level: "Advanced",
    icon: "📦",
  },
] as const;

export const transactions = [
  { id: "1", type: "deposit", label: "Wallet top-up (Paystack)", amount: 50000, date: "Today" },
  { id: "2", type: "withdraw", label: "Sale payout", amount: 45000, date: "Yesterday" },
  { id: "3", type: "transfer", label: "TOP promo", amount: -5000, date: "2 days ago" },
  { id: "4", type: "transfer", label: "Premium subscription", amount: -11200, date: "1 week ago" },
] as const;

export const partners = [
  {
    id: "1",
    name: "Consumer Protection Council",
    type: "Public service",
    verified: true,
    logo: "🏛️",
  },
  { id: "2", name: "Payment Safety Network", type: "Payments", verified: true, logo: "🤝" },
  { id: "3", name: "HomeStyle Furniture", type: "Company", verified: true, logo: "🛋️" },
  { id: "4", name: "BrightGrid Energy", type: "Company", verified: false, logo: "☀️" },
] as const;

export const posts = [
  {
    id: "1",
    author: "Aisha M.",
    handle: "@aisha",
    time: "2h",
    content: "Just listed my home-office sofa set. Buyers have been so helpful here!",
    likes: 128,
    comments: 24,
  },
  {
    id: "2",
    author: "TechHub NG",
    handle: "@techhub",
    time: "5h",
    content: "Fresh gadgets have arrived in our Abuja store. Send a message for details.",
    likes: 89,
    comments: 12,
  },
  {
    id: "3",
    author: "Ibrahim K.",
    handle: "@ibrahim",
    time: "1d",
    content: "Anyone know a trusted mover for a small apartment in Kano?",
    likes: 45,
    comments: 31,
  },
] as const;

export const news = [
  {
    id: "1",
    title: "New consumer-protection guidance for online shoppers",
    source: "MarketX News",
    time: "1h ago",
  },
  {
    id: "2",
    title: "Smarter shipping options now available in major cities",
    source: "Business Update",
    time: "4h ago",
  },
  {
    id: "3",
    title: "Local sellers report strong demand for home essentials",
    source: "Retail Watch",
    time: "1d ago",
  },
] as const;

export const notifications = [
  {
    id: "1",
    title: "New item near you",
    body: "A new listing matches your saved search.",
    time: "10m",
    unread: true,
  },
  {
    id: "2",
    title: "Price update",
    body: "A saved item has a new price.",
    time: "2h",
    unread: true,
  },
  {
    id: "3",
    title: "New message",
    body: "A seller replied to your enquiry.",
    time: "1d",
    unread: false,
  },
] as const;

export const SUBSCRIPTION_PLANS = [
  { id: "free", name: "Free", price: 0, listings: 5, perks: ["5 listings", "Standard visibility"] },
  {
    id: "basic",
    name: "Basic",
    price: 5600,
    listings: 20,
    perks: ["20 listings", "Priority support"],
  },
  {
    id: "premium",
    name: "Premium",
    price: 11200,
    listings: 50,
    perks: ["50 listings", "Priority placement", "Auto-renew"],
  },
  {
    id: "vip",
    name: "VIP",
    price: 18900,
    listings: 100,
    perks: ["100 listings", "Boost credits", "Priority support"],
  },
  {
    id: "vip-gold",
    name: "VIP Gold",
    price: 24325,
    listings: 150,
    perks: ["150 listings", "Weekly boost", "Cashback"],
  },
  {
    id: "diamond-gold",
    name: "Diamond Gold",
    price: 36750,
    listings: 250,
    perks: ["250 listings", "Featured placement", "Cashback"],
  },
  {
    id: "diamond-elite",
    name: "Diamond Elite",
    price: 45850,
    listings: 400,
    perks: ["400 listings", "Premium support", "Auto-renew"],
  },
  {
    id: "enterprise-gold",
    name: "Enterprise Gold",
    price: 63525,
    listings: 750,
    perks: ["750 listings", "Team tools", "Featured placement"],
  },
  {
    id: "enterprise-elite",
    name: "Enterprise Elite",
    price: 135450,
    listings: 1500,
    perks: ["1,500 listings", "Dedicated support", "Priority visibility"],
  },
  {
    id: "enterprise-lux",
    name: "Enterprise Lux",
    price: 203350,
    listings: 3000,
    perks: ["3,000 listings", "Account manager", "Maximum visibility"],
  },
] as const;

export const PROMOTION_PLANS = [
  { id: "none", name: "No promo", price: 0, duration: "Standard visibility", detail: "Free" },
  { id: "basic", name: "Basic Boost", price: 2500, duration: "7 days", detail: "Top of search" },
  {
    id: "top",
    name: "TOP Promo",
    price: 5000,
    duration: "7 days",
    detail: "Top spot + 15× traffic",
  },
  {
    id: "premium",
    name: "Premium Boost",
    price: 15000,
    duration: "30 days",
    detail: "Top spot + badge + 30× traffic",
  },
] as const;

export const PRICING = {
  promoTop: 5000,
  promoWeek: 2500,
  promoMonth: 15000,
  jobPromoMin: 2000,
  jobPromoMax: 3000,
  bluetekMonthly: 5600,
} as const;
