export const LOCATIONS = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;
export type LocationName = (typeof LOCATIONS)[number];

export const products = [
  {
    id: "1",
    name: "Maize (100kg)",
    price: 45000,
    seller: "GreenFields Ltd",
    rating: 4.6,
    image: "🌽",
    location: "Kano",
    promoted: true,
  },
  {
    id: "2",
    name: "Fresh Tomatoes",
    price: 12000,
    seller: "Kano Farms",
    rating: 4.4,
    image: "🍅",
    location: "Kano",
    promoted: false,
  },
  {
    id: "3",
    name: "Rice Paddy (100kg)",
    price: 65000,
    seller: "Delta Agro",
    rating: 4.8,
    image: "🌾",
    location: "Delta",
    promoted: true,
  },
  {
    id: "4",
    name: "Cassava Tubers",
    price: 8000,
    seller: "Ogun Coop",
    rating: 4.2,
    image: "🥔",
    location: "Ogun",
    promoted: false,
  },
  {
    id: "5",
    name: "Palm Oil (25L)",
    price: 32000,
    seller: "Cross River Growers",
    rating: 4.7,
    image: "🫒",
    location: "Cross River",
    promoted: false,
  },
  {
    id: "6",
    name: "Yam Tubers",
    price: 18000,
    seller: "Benue Farms",
    rating: 4.5,
    image: "🍠",
    location: "Benue",
    promoted: false,
  },
  {
    id: "7",
    name: "Groundnut (50kg)",
    price: 22000,
    seller: "Kaduna Traders",
    rating: 4.3,
    image: "🥜",
    location: "Kaduna",
    promoted: true,
  },
  {
    id: "8",
    name: "Millet Grain (50kg)",
    price: 15000,
    seller: "Sahel Cooperative",
    rating: 4.1,
    image: "🌾",
    location: "Katsina",
    promoted: false,
  },
  {
    id: "9",
    name: "Fresh Okra Basket",
    price: 9500,
    seller: "Abia Fresh Market",
    rating: 4.5,
    image: "🥬",
    location: "Abia",
    promoted: false,
  },
  {
    id: "10",
    name: "Poultry Feed (25kg)",
    price: 18500,
    seller: "Adamawa Poultry",
    rating: 4.2,
    image: "🐓",
    location: "Adamawa",
    promoted: false,
  },
  {
    id: "11",
    name: "Plantain Bunch",
    price: 14000,
    seller: "Akwa Ibom Farms",
    rating: 4.6,
    image: "🍌",
    location: "Akwa Ibom",
    promoted: false,
  },
  {
    id: "12",
    name: "Ugu Vegetable Bundle",
    price: 7000,
    seller: "Anambra Green Hub",
    rating: 4.4,
    image: "🥬",
    location: "Anambra",
    promoted: false,
  },
  {
    id: "13",
    name: "Soya Beans (50kg)",
    price: 28000,
    seller: "Bauchi Harvest",
    rating: 4.3,
    image: "🫘",
    location: "Bauchi",
    promoted: false,
  },
  {
    id: "14",
    name: "Fresh Catfish (10kg)",
    price: 36000,
    seller: "Bayelsa Fishers",
    rating: 4.7,
    image: "🐟",
    location: "Bayelsa",
    promoted: true,
  },
  {
    id: "15",
    name: "Sesame Seeds (50kg)",
    price: 52000,
    seller: "Borno Agro Link",
    rating: 4.1,
    image: "🌱",
    location: "Borno",
    promoted: false,
  },
  {
    id: "16",
    name: "Cocoa Beans (25kg)",
    price: 48000,
    seller: "Ebonyi Cocoa Co.",
    rating: 4.5,
    image: "🍫",
    location: "Ebonyi",
    promoted: false,
  },
  {
    id: "17",
    name: "Rubber Seedlings",
    price: 12000,
    seller: "Edo Nursery",
    rating: 4.2,
    image: "🌳",
    location: "Edo",
    promoted: false,
  },
  {
    id: "18",
    name: "Fresh Ginger (25kg)",
    price: 30000,
    seller: "Ekiti Roots",
    rating: 4.6,
    image: "🫚",
    location: "Ekiti",
    promoted: false,
  },
  {
    id: "19",
    name: "Broiler Chickens (10)",
    price: 52000,
    seller: "Enugu Poultry",
    rating: 4.4,
    image: "🐔",
    location: "Enugu",
    promoted: false,
  },
  {
    id: "20",
    name: "Organic Fertilizer (50kg)",
    price: 17000,
    seller: "Abuja Agro Store",
    rating: 4.5,
    image: "🪴",
    location: "FCT Abuja",
    promoted: true,
  },
  {
    id: "21",
    name: "Onion Bag (50kg)",
    price: 38000,
    seller: "Gombe Traders",
    rating: 4.3,
    image: "🧅",
    location: "Gombe",
    promoted: false,
  },
  {
    id: "22",
    name: "Avocado Crate",
    price: 21000,
    seller: "Imo Produce",
    rating: 4.1,
    image: "🥑",
    location: "Imo",
    promoted: false,
  },
  {
    id: "23",
    name: "Watermelon (Bulk)",
    price: 25000,
    seller: "Jigawa Melons",
    rating: 4.6,
    image: "🍉",
    location: "Jigawa",
    promoted: false,
  },
  {
    id: "24",
    name: "Dried Fish Basket",
    price: 42000,
    seller: "Kebbi Fisheries",
    rating: 4.2,
    image: "🐠",
    location: "Kebbi",
    promoted: false,
  },
  {
    id: "25",
    name: "Cashew Nuts (25kg)",
    price: 47000,
    seller: "Kogi Cashew Hub",
    rating: 4.7,
    image: "🥜",
    location: "Kogi",
    promoted: true,
  },
  {
    id: "26",
    name: "Shea Butter (10kg)",
    price: 35000,
    seller: "Kwara Naturals",
    rating: 4.4,
    image: "🧈",
    location: "Kwara",
    promoted: false,
  },
  {
    id: "27",
    name: "Smoked Fish Pack",
    price: 28000,
    seller: "Lagos Seafood",
    rating: 4.5,
    image: "🐟",
    location: "Lagos",
    promoted: false,
  },
  {
    id: "28",
    name: "Goat Feed (25kg)",
    price: 14500,
    seller: "Nasarawa Livestock",
    rating: 4.2,
    image: "🐐",
    location: "Nasarawa",
    promoted: false,
  },
  {
    id: "29",
    name: "Fresh Cabbage Crate",
    price: 16000,
    seller: "Plateau Vegetables",
    rating: 4.6,
    image: "🥬",
    location: "Plateau",
    promoted: false,
  },
  {
    id: "30",
    name: "Mango Basket",
    price: 19000,
    seller: "Taraba Orchards",
    rating: 4.3,
    image: "🥭",
    location: "Taraba",
    promoted: false,
  },
] as const;

export const jobs = [
  {
    id: "1",
    title: "Farm Manager",
    company: "GreenFields Ltd",
    location: "Kano",
    salary: "₦250k/mo",
    type: "Full-time",
    promoted: true,
  },
  {
    id: "2",
    title: "Irrigation Technician",
    company: "Delta Agro",
    location: "Delta",
    salary: "₦180k/mo",
    type: "Contract",
    promoted: false,
  },
  {
    id: "3",
    title: "Livestock Handler",
    company: "Sahel Ranch",
    location: "Kaduna",
    salary: "₦120k/mo",
    type: "Full-time",
    promoted: false,
  },
  {
    id: "4",
    title: "Agro Sales Rep",
    company: "FarmX Partner",
    location: "Lagos",
    salary: "₦200k/mo",
    type: "Remote",
    promoted: false,
  },
  {
    id: "5",
    title: "Warehouse Supervisor",
    company: "Kano Farms",
    location: "Kano",
    salary: "₦150k/mo",
    type: "Full-time",
    promoted: true,
  },
] as const;

export const tutorials = [
  {
    id: "1",
    title: "Modern Irrigation Techniques",
    duration: "12 min",
    level: "Beginner",
    icon: "💧",
  },
  {
    id: "2",
    title: "Poultry Disease Prevention",
    duration: "18 min",
    level: "Intermediate",
    icon: "🐔",
  },
  { id: "3", title: "Organic Fertilizer Making", duration: "9 min", level: "Beginner", icon: "🌱" },
  { id: "4", title: "Post-harvest Storage", duration: "15 min", level: "Advanced", icon: "📦" },
] as const;

export const transactions = [
  { id: "1", type: "deposit", label: "Wallet top-up (Paystack)", amount: 50000, date: "Today" },
  { id: "2", type: "withdraw", label: "Sold 100kg maize", amount: 45000, date: "Yesterday" },
  { id: "3", type: "transfer", label: "Listing fee — Maize", amount: -2000, date: "2 days ago" },
  { id: "4", type: "transfer", label: "Bluetek subscription", amount: -4500, date: "1 week ago" },
] as const;

export const partners = [
  { id: "1", name: "Ministry of Agriculture", type: "Government", verified: true, logo: "🏛️" },
  { id: "2", name: "AgroFund NGO", type: "NGO", verified: true, logo: "🤝" },
  { id: "3", name: "GreenFields Ltd", type: "Company", verified: true, logo: "🌾" },
  { id: "4", name: "Sahel Ranch", type: "Company", verified: false, logo: "🐄" },
] as const;

export const posts = [
  {
    id: "1",
    author: "Aisha M.",
    handle: "@aisha",
    time: "2h",
    content: "Just harvested 3 tons of tomatoes this season! Alhamdulillah 🍅",
    likes: 128,
    comments: 24,
  },
  {
    id: "2",
    author: "GreenFields Ltd",
    handle: "@greenfields",
    time: "5h",
    content: "We're hiring farm managers in Kano. Apply through FarmX Jobs.",
    likes: 89,
    comments: 12,
  },
  {
    id: "3",
    author: "Ibrahim K.",
    handle: "@ibrahim",
    time: "1d",
    content: "Anyone using drip irrigation? Looking for tips on maintenance.",
    likes: 45,
    comments: 31,
  },
] as const;

export const news = [
  {
    id: "1",
    title: "Government launches ₦50B agro-loan scheme",
    source: "FarmX News",
    time: "1h ago",
  },
  {
    id: "2",
    title: "Rainy season forecast: above-average yields expected",
    source: "NiMet",
    time: "4h ago",
  },
  {
    id: "3",
    title: "New export corridor opens for African crops",
    source: "Enterprise Update",
    time: "1d ago",
  },
] as const;

export const notifications = [
  {
    id: "1",
    title: "New product from GreenFields",
    body: "Fresh maize now available",
    time: "10m",
    unread: true,
  },
  {
    id: "2",
    title: "Payment received",
    body: "₦45,000 credited to wallet",
    time: "2h",
    unread: true,
  },
  { id: "3", title: "New follower", body: "Sahel Ranch followed you", time: "1d", unread: false },
] as const;

export const PRICING = {
  listingFee: 2000,
  promoTop: 2799,
  promoWeek: 3000,
  promoMonth: 5200,
  jobPromoMin: 2000,
  jobPromoMax: 3000,
  bluetekMonthly: 4500,
} as const;
