import type { Lang } from "@/lib/i18n";

const en: Record<string, string> = {
  "group.account": "Account",
  "group.preferences": "Preferences",
  "group.marketplace": "Marketplace",
  "group.payments": "Payments & services",
  "group.trust": "Trust & safety",
  "group.activity": "Activity",
  "group.support": "Support",
  "item.personal-info.label": "Personal information",
  "item.personal-info.description": "Name, photo, username, phone and email",
  "item.business.label": "Business profile",
  "item.business.description": "Business identity, public details and verification",
  "item.login-methods.label": "Login & connected accounts",
  "item.login-methods.description": "Email, phone and connected sign-in methods",
  "item.security.label": "Password & security",
  "item.security.description": "Password, verification and account protection",
  "item.language.label": "Language & region",
  "item.language.description": "Language, country, currency and date preferences",
  "item.notifications.label": "Notifications",
  "item.notifications.description": "Account, marketplace, social and payment alerts",
  "item.privacy.label": "Privacy",
  "item.privacy.description": "Visibility, search and activity controls",
  "item.communication.label": "Communication",
  "item.communication.description": "Messaging, calls, receipts and indicators",
  "item.buying.label": "Buying preferences",
  "item.buying.description": "Categories, delivery and preferred locations",
  "item.selling.label": "Selling & posting",
  "item.selling.description": "Plan, posting allowance and listing controls",
  "item.saved-searches.label": "Saved searches",
  "item.saved-searches.description": "Search criteria and alert preferences",
  "item.location.label": "Location preferences",
  "item.location.description": "Marketplace location and search radius",
  "item.balance.label": "Goall26 Balance",
  "item.balance.description": "Service credits and available funds",
  "item.payments.label": "Payment history",
  "item.payments.description": "Verified subscriptions, boosts and service payments",
  "item.subscription.label": "Subscription",
  "item.subscription.description": "Plan, expiry, usage and billing options",
  "item.boosting.label": "Boosting",
  "item.boosting.description": "Active promotions and boost history",
  "item.verification.label": "Verification",
  "item.verification.description": "Email, phone, identity, business and seller status",
  "item.blocked.label": "Blocked users",
  "item.blocked.description": "Review and manage blocked accounts",
  "item.safety.label": "Reports & safety",
  "item.safety.description": "Report concerns and read safety guidance",
  "item.activity.label": "My activity",
  "item.activity.description": "Ads, searches, saves, follows and community activity",
  "item.recently-viewed.label": "Recently viewed",
  "item.recently-viewed.description": "Listings you opened recently",
  "item.saved.label": "Saved ads",
  "item.saved.description": "Saved listings and current availability",
  "item.support.label": "Help & support",
  "item.support.description": "Help centre, support and problem reports",
  "item.legal.label": "Terms & policies",
  "item.legal.description": "Terms, privacy, marketplace and payment rules",
  "item.about.label": "About Goall26",
  "item.about.description": "Version, mission, contact and licences",
};

const ha: Record<string, string> = {
  "group.account": "Asusu",
  "group.preferences": "Zaɓuɓɓuka",
  "group.marketplace": "Kasuwanci",
  "group.payments": "Biya da ayyuka",
  "group.trust": "Aminci da tsaro",
  "group.activity": "Ayyuka",
  "group.support": "Taimako",
  "item.personal-info.label": "Bayanan kaina",
  "item.personal-info.description": "Suna, hoto, username, waya da email",
  "item.business.label": "Bayanan kasuwanci",
  "item.business.description": "Shaidar kasuwanci da tantancewa",
  "item.login-methods.label": "Shiga da asusun da aka haɗa",
  "item.login-methods.description": "Hanyoyin shiga asusu",
  "item.security.label": "Kalmar sirri da tsaro",
  "item.security.description": "Kare asusunka da tabbatarwa",
  "item.language.label": "Harshe da yanki",
  "item.language.description": "Harshe, ƙasa, kuɗi da kwanan wata",
  "item.notifications.label": "Sanarwa",
  "item.notifications.description": "Sanarwar asusu, kasuwa da biyan kuɗi",
  "item.privacy.label": "Sirri",
  "item.privacy.description": "Abin da mutane za su gani",
  "item.communication.label": "Sadarwa",
  "item.communication.description": "Saƙonni, kira da alamu",
  "item.buying.label": "Zaɓin saye",
  "item.buying.description": "Rukuni, isarwa da wuri",
  "item.selling.label": "Sayarwa da saka kaya",
  "item.selling.description": "Tsari, iyakar talla da kaya",
  "item.saved-searches.label": "Binciken da aka ajiye",
  "item.saved-searches.description": "Bincike da sanarwarsa",
  "item.location.label": "Zaɓin wuri",
  "item.location.description": "Wurin kasuwa da nisan bincike",
  "item.balance.label": "Ma'aunin Goall26",
  "item.balance.description": "Kuɗin ayyuka da sauran kuɗi",
  "item.payments.label": "Tarihin biya",
  "item.payments.description": "Biyan kuɗin da uwar garke ta tabbatar",
  "item.subscription.label": "Shirin biyan kuɗi",
  "item.subscription.description": "Shiri, ƙarewa da amfani",
  "item.boosting.label": "Tallata kaya",
  "item.boosting.description": "Tallace-tallacen da ke aiki",
  "item.verification.label": "Tantancewa",
  "item.verification.description": "Email, waya, shaida da kasuwanci",
  "item.blocked.label": "Masu amfani da aka toshe",
  "item.blocked.description": "Duba asusun da aka toshe",
  "item.safety.label": "Rahoto da tsaro",
  "item.safety.description": "Rahoto da shawarwarin tsaro",
  "item.activity.label": "Ayyukana",
  "item.activity.description": "Tallace-tallace, bincike, ajiya da biye",
  "item.recently-viewed.label": "Abubuwan da aka kalla kwanan nan",
  "item.recently-viewed.description": "Kayayyakin da ka buɗe",
  "item.saved.label": "Kayayyakin da aka ajiye",
  "item.saved.description": "Kayayyakin da aka adana",
  "item.support.label": "Taimako",
  "item.support.description": "Tambayoyi da rahoton matsala",
  "item.legal.label": "Sharuɗɗa da manufofi",
  "item.legal.description": "Sirri, kasuwa da biyan kuɗi",
  "item.about.label": "Game da Goall26",
  "item.about.description": "Sigar manhaja da bayanai",
};

const ig: Record<string, string> = {
  "group.account": "Akaụntụ",
  "group.preferences": "Nhọrọ",
  "group.marketplace": "Ahịa",
  "group.payments": "Ịkwụ ụgwọ na ọrụ",
  "group.trust": "Ntụkwasị obi na nchekwa",
  "group.activity": "Ọrụ",
  "group.support": "Nkwado",
  "item.personal-info.label": "Ozi nkeonwe",
  "item.personal-info.description": "Aha, foto, aha njirimara, ekwentị na email",
  "item.business.label": "Profaịlụ azụmahịa",
  "item.business.description": "Ozi azụmahịa na nkwenye",
  "item.login-methods.label": "Nbanye na akaụntụ ejikọtara",
  "item.login-methods.description": "Ụzọ nbanye",
  "item.security.label": "Paswọọdụ na nchekwa",
  "item.security.description": "Nchekwa akaụntụ",
  "item.language.label": "Asụsụ na mpaghara",
  "item.language.description": "Asụsụ, obodo, ego na ụbọchị",
  "item.notifications.label": "Ọkwa",
  "item.notifications.description": "Ọkwa akaụntụ, ahịa na ịkwụ ụgwọ",
  "item.privacy.label": "Nzuzo",
  "item.privacy.description": "Ihe ndị ọzọ ga-ahụ",
  "item.communication.label": "Nkwukọrịta",
  "item.communication.description": "Ozi, oku na akara",
  "item.buying.label": "Nhọrọ ịzụ ahịa",
  "item.buying.description": "Ụdị, nnyefe na ebe",
  "item.selling.label": "Ịre na itinye ihe",
  "item.selling.description": "Atụmatụ na oke mgbasa ozi",
  "item.saved-searches.label": "Nchọgharị echekwara",
  "item.saved-searches.description": "Nchọgharị na ọkwa",
  "item.location.label": "Nhọrọ ebe",
  "item.location.description": "Ebe ahịa na anya nchọgharị",
  "item.balance.label": "Balance Goall26",
  "item.balance.description": "Ego ọrụ na ego dị",
  "item.payments.label": "Akụkọ ịkwụ ụgwọ",
  "item.payments.description": "Ịkwụ ụgwọ nke sava kwadoro",
  "item.subscription.label": "Ndebanye aha",
  "item.subscription.description": "Atụmatụ, ngwụcha na ojiji",
  "item.boosting.label": "Ịkwalite",
  "item.boosting.description": "Mgbasa ozi na-arụ ọrụ",
  "item.verification.label": "Nkwenye",
  "item.verification.description": "Email, ekwentị na azụmahịa",
  "item.blocked.label": "Ndị akpọchiri",
  "item.blocked.description": "Jikwaa ndị akpọchiri",
  "item.safety.label": "Akụkọ na nchekwa",
  "item.safety.description": "Kọọ nsogbu ma gụọ ndụmọdụ",
  "item.activity.label": "Ọrụ m",
  "item.activity.description": "Mgbasa ozi, nchọgharị na nchekwa",
  "item.recently-viewed.label": "A hụrụ nso nso a",
  "item.recently-viewed.description": "Ndepụta ị mepere",
  "item.saved.label": "Mgbasa ozi echekwara",
  "item.saved.description": "Ndepụta echekwara",
  "item.support.label": "Nkwado",
  "item.support.description": "Ajụjụ na akụkọ nsogbu",
  "item.legal.label": "Usoro na iwu",
  "item.legal.description": "Nzuzo, ahịa na ịkwụ ụgwọ",
  "item.about.label": "Banyere Goall26",
  "item.about.description": "Ụdị ngwa na ozi",
};

const yo: Record<string, string> = {
  "group.account": "Àkọọ́lẹ̀",
  "group.preferences": "Àwọn yíyan",
  "group.marketplace": "Ọjà",
  "group.payments": "Ìsanwó àti iṣẹ́",
  "group.trust": "Ìgbẹ́kẹ̀lé àti ààbò",
  "group.activity": "Ìṣe",
  "group.support": "Ìrànwọ́",
  "item.personal-info.label": "Alaye ti ara ẹni",
  "item.personal-info.description": "Orúkọ, àwòrán, orúkọ olumulo, fóònù àti imeeli",
  "item.business.label": "Àkọọ́lẹ̀ ìṣòwò",
  "item.business.description": "Alaye ìṣòwò àti ìjẹ́rìísí",
  "item.login-methods.label": "Wíwọlé àti àwọn àkọọ́lẹ̀",
  "item.login-methods.description": "Àwọn ọ̀nà wíwọlé",
  "item.security.label": "Ọ̀rọ̀ aṣínà àti ààbò",
  "item.security.description": "Ààbò àkọọ́lẹ̀",
  "item.language.label": "Èdè àti agbègbè",
  "item.language.description": "Èdè, orílẹ̀-èdè, owó àti ọjọ́",
  "item.notifications.label": "Àwọn ìkìlọ̀",
  "item.notifications.description": "Ìkìlọ̀ àkọọ́lẹ̀, ọjà àti ìsanwó",
  "item.privacy.label": "Àṣírí",
  "item.privacy.description": "Ohun tí àwọn mìíràn lè rí",
  "item.communication.label": "Ìbánisọ̀rọ̀",
  "item.communication.description": "Ifiranṣẹ́, ìpè àti àmì",
  "item.buying.label": "Àwọn yíyan rírà",
  "item.buying.description": "Ẹ̀ka, ìfiránṣẹ́ àti ibi",
  "item.selling.label": "Títà àti fífi ọjà sílẹ̀",
  "item.selling.description": "Ètò àti ààlà ìpolówó",
  "item.saved-searches.label": "Àwọn àwárí tí a pamọ́",
  "item.saved-searches.description": "Àwárí àti ìkìlọ̀",
  "item.location.label": "Yíyan ibi",
  "item.location.description": "Ibi ọjà àti ààlà àwárí",
  "item.balance.label": "Ìwọ̀n Goall26",
  "item.balance.description": "Owó iṣẹ́ àti owó tó wà",
  "item.payments.label": "Ìtàn ìsanwó",
  "item.payments.description": "Ìsanwó tí olupin ti jẹ́rìísí",
  "item.subscription.label": "Ìforúkọsílẹ̀",
  "item.subscription.description": "Ètò, ìparí àti lílo",
  "item.boosting.label": "Ìgbéga",
  "item.boosting.description": "Ìpolówó tó ń ṣiṣẹ́",
  "item.verification.label": "Ìjẹ́rìísí",
  "item.verification.description": "Imeeli, fóònù àti ìṣòwò",
  "item.blocked.label": "Àwọn tí a dènà",
  "item.blocked.description": "Ṣàkóso àwọn tí a dènà",
  "item.safety.label": "Ìròyìn àti ààbò",
  "item.safety.description": "Ròyìn ìṣòro kí o sì ka ìmọ̀ràn",
  "item.activity.label": "Ìṣe mi",
  "item.activity.description": "Ìpolówó, àwárí àti àwọn ohun tí a pamọ́",
  "item.recently-viewed.label": "Tí a rí láìpẹ́",
  "item.recently-viewed.description": "Àwọn ọjà tí o ṣí",
  "item.saved.label": "Àwọn ìpolówó tí a pamọ́",
  "item.saved.description": "Àwọn ọjà tí a pamọ́",
  "item.support.label": "Ìrànwọ́",
  "item.support.description": "Ìbéèrè àti ìròyìn ìṣòro",
  "item.legal.label": "Àwọn òfin àti ìlànà",
  "item.legal.description": "Àṣírí, ọjà àti ìsanwó",
  "item.about.label": "Nípa Goall26",
  "item.about.description": "Ẹ̀dà app àti àlàyé",
};

const kr: Record<string, string> = {
  "group.account": "Asusu",
  "group.preferences": "Zaɓe",
  "group.marketplace": "Kasuwanci",
  "group.payments": "Biya da ayyuka",
  "group.trust": "Aminci da tsaro",
  "group.activity": "Ayyuka",
  "group.support": "Taimako",
  ...ha,
};

const dictionaries: Record<Lang, Record<string, string>> = { en, ha, ig, yo, kr };

export function settingsText(lang: Lang, key: string, fallback?: string) {
  return dictionaries[lang]?.[key] ?? en[key] ?? fallback ?? key;
}
