/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BuyerProtectionRouteImport } from './routes/buyer-protection'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as DisputesRouteImport } from './routes/disputes'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PostRouteImport } from './routes/post'
import { Route as PostCommunityRouteImport } from './routes/post-community'
import { Route as PostJobRouteImport } from './routes/post-job'
import { Route as PostProductRouteImport } from './routes/post-product'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as CommunityIdRouteImport } from './routes/community.$id'
import { Route as EditAdIdRouteImport } from './routes/edit-ad.$id'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as LearnCourseIdRouteImport } from './routes/learn.$courseId'
import { Route as MarketCategoriesRouteImport } from './routes/market.categories'
import { Route as MarketSearchRouteImport } from './routes/market.search'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ProfileCenterSectionRouteImport } from './routes/profile-center.$section'
import { Route as SettingsSectionRouteImport } from './routes/settings.$section'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ApiPaymentsWebhookRouteImport } from './routes/api.payments.webhook'
import { Route as MarketCategoryCategoryRouteImport } from './routes/market.category.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerProtectionRoute = BuyerProtectionRouteImport.update({
  id: '/buyer-protection',
  path: '/buyer-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesRoute = DisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const PostCommunityRoute = PostCommunityRouteImport.update({
  id: '/post-community',
  path: '/post-community',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobRoute = PostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const PostProductRoute = PostProductRouteImport.update({
  id: '/post-product',
  path: '/post-product',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIdRoute = CommunityIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CommunityRoute,
} as any)
const EditAdIdRoute = EditAdIdRouteImport.update({
  id: '/edit-ad/$id',
  path: '/edit-ad/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)
const LearnCourseIdRoute = LearnCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => LearnRoute,
} as any)
const MarketCategoriesRoute = MarketCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => MarketRoute,
} as any)
const MarketSearchRoute = MarketSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MarketRoute,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MessagesRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCenterSectionRoute = ProfileCenterSectionRouteImport.update({
  id: '/profile-center/$section',
  path: '/profile-center/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => SettingsRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsWebhookRoute = ApiPaymentsWebhookRouteImport.update({
  id: '/api/payments/webhook',
  path: '/api/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketCategoryCategoryRoute = MarketCategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => MarketRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/buyer-protection': typeof BuyerProtectionRoute
  '/community': typeof CommunityRouteWithChildren
  '/company': typeof CompanyRoute
  '/disputes': typeof DisputesRoute
  '/edit-profile': typeof EditProfileRoute
  '/faq': typeof FaqRoute
  '/fleet': typeof FleetRoute
  '/inventory': typeof InventoryRoute
  '/jobs': typeof JobsRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/plans': typeof PlansRoute
  '/post': typeof PostRoute
  '/post-community': typeof PostCommunityRoute
  '/post-job': typeof PostJobRoute
  '/post-product': typeof PostProductRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRoute
  '/subscribe': typeof SubscribeRoute
  '/upgrade': typeof UpgradeRoute
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wallet': typeof WalletRoute
  '/c/$slug': typeof CSlugRoute
  '/community/$id': typeof CommunityIdRoute
  '/edit-ad/$id': typeof EditAdIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/market/categories': typeof MarketCategoriesRoute
  '/market/search': typeof MarketSearchRoute
  '/messages/$id': typeof MessagesIdRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/product/$id': typeof ProductIdRoute
  '/profile-center/$section': typeof ProfileCenterSectionRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/u/$username': typeof UUsernameRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/market/category/$category': typeof MarketCategoryCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/buyer-protection': typeof BuyerProtectionRoute
  '/community': typeof CommunityRouteWithChildren
  '/company': typeof CompanyRoute
  '/disputes': typeof DisputesRoute
  '/edit-profile': typeof EditProfileRoute
  '/faq': typeof FaqRoute
  '/fleet': typeof FleetRoute
  '/inventory': typeof InventoryRoute
  '/jobs': typeof JobsRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/plans': typeof PlansRoute
  '/post': typeof PostRoute
  '/post-community': typeof PostCommunityRoute
  '/post-job': typeof PostJobRoute
  '/post-product': typeof PostProductRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRoute
  '/subscribe': typeof SubscribeRoute
  '/upgrade': typeof UpgradeRoute
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wallet': typeof WalletRoute
  '/c/$slug': typeof CSlugRoute
  '/community/$id': typeof CommunityIdRoute
  '/edit-ad/$id': typeof EditAdIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/market/categories': typeof MarketCategoriesRoute
  '/market/search': typeof MarketSearchRoute
  '/messages/$id': typeof MessagesIdRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/product/$id': typeof ProductIdRoute
  '/profile-center/$section': typeof ProfileCenterSectionRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/u/$username': typeof UUsernameRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/market/category/$category': typeof MarketCategoryCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/buyer-protection': typeof BuyerProtectionRoute
  '/community': typeof CommunityRouteWithChildren
  '/company': typeof CompanyRoute
  '/disputes': typeof DisputesRoute
  '/edit-profile': typeof EditProfileRoute
  '/faq': typeof FaqRoute
  '/fleet': typeof FleetRoute
  '/inventory': typeof InventoryRoute
  '/jobs': typeof JobsRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/plans': typeof PlansRoute
  '/post': typeof PostRoute
  '/post-community': typeof PostCommunityRoute
  '/post-job': typeof PostJobRoute
  '/post-product': typeof PostProductRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRoute
  '/subscribe': typeof SubscribeRoute
  '/upgrade': typeof UpgradeRoute
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wallet': typeof WalletRoute
  '/c/$slug': typeof CSlugRoute
  '/community/$id': typeof CommunityIdRoute
  '/edit-ad/$id': typeof EditAdIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/market/categories': typeof MarketCategoriesRoute
  '/market/search': typeof MarketSearchRoute
  '/messages/$id': typeof MessagesIdRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/product/$id': typeof ProductIdRoute
  '/profile-center/$section': typeof ProfileCenterSectionRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/u/$username': typeof UUsernameRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/market/category/$category': typeof MarketCategoryCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/buyer-protection'
    | '/community'
    | '/company'
    | '/disputes'
    | '/edit-profile'
    | '/faq'
    | '/fleet'
    | '/inventory'
    | '/jobs'
    | '/learn'
    | '/login'
    | '/market'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/plans'
    | '/post'
    | '/post-community'
    | '/post-job'
    | '/post-product'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/robots.txt'
    | '/saved'
    | '/search'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/staff'
    | '/subscribe'
    | '/upgrade'
    | '/verify'
    | '/verify-email'
    | '/wallet'
    | '/c/$slug'
    | '/community/$id'
    | '/edit-ad/$id'
    | '/jobs/$id'
    | '/learn/$courseId'
    | '/market/categories'
    | '/market/search'
    | '/messages/$id'
    | '/oauth/callback'
    | '/product/$id'
    | '/profile-center/$section'
    | '/settings/$section'
    | '/u/$username'
    | '/api/payments/webhook'
    | '/market/category/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/buyer-protection'
    | '/community'
    | '/company'
    | '/disputes'
    | '/edit-profile'
    | '/faq'
    | '/fleet'
    | '/inventory'
    | '/jobs'
    | '/learn'
    | '/login'
    | '/market'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/plans'
    | '/post'
    | '/post-community'
    | '/post-job'
    | '/post-product'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/robots.txt'
    | '/saved'
    | '/search'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/staff'
    | '/subscribe'
    | '/upgrade'
    | '/verify'
    | '/verify-email'
    | '/wallet'
    | '/c/$slug'
    | '/community/$id'
    | '/edit-ad/$id'
    | '/jobs/$id'
    | '/learn/$courseId'
    | '/market/categories'
    | '/market/search'
    | '/messages/$id'
    | '/oauth/callback'
    | '/product/$id'
    | '/profile-center/$section'
    | '/settings/$section'
    | '/u/$username'
    | '/api/payments/webhook'
    | '/market/category/$category'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/buyer-protection'
    | '/community'
    | '/company'
    | '/disputes'
    | '/edit-profile'
    | '/faq'
    | '/fleet'
    | '/inventory'
    | '/jobs'
    | '/learn'
    | '/login'
    | '/market'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/plans'
    | '/post'
    | '/post-community'
    | '/post-job'
    | '/post-product'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/robots.txt'
    | '/saved'
    | '/search'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/staff'
    | '/subscribe'
    | '/upgrade'
    | '/verify'
    | '/verify-email'
    | '/wallet'
    | '/c/$slug'
    | '/community/$id'
    | '/edit-ad/$id'
    | '/jobs/$id'
    | '/learn/$courseId'
    | '/market/categories'
    | '/market/search'
    | '/messages/$id'
    | '/oauth/callback'
    | '/product/$id'
    | '/profile-center/$section'
    | '/settings/$section'
    | '/u/$username'
    | '/api/payments/webhook'
    | '/market/category/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BuyerProtectionRoute: typeof BuyerProtectionRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  CompanyRoute: typeof CompanyRoute
  DisputesRoute: typeof DisputesRoute
  EditProfileRoute: typeof EditProfileRoute
  FaqRoute: typeof FaqRoute
  FleetRoute: typeof FleetRoute
  InventoryRoute: typeof InventoryRoute
  JobsRoute: typeof JobsRouteWithChildren
  LearnRoute: typeof LearnRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRouteWithChildren
  MessagesRoute: typeof MessagesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  PlansRoute: typeof PlansRoute
  PostRoute: typeof PostRoute
  PostCommunityRoute: typeof PostCommunityRoute
  PostJobRoute: typeof PostJobRoute
  PostProductRoute: typeof PostProductRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaffRoute: typeof StaffRoute
  SubscribeRoute: typeof SubscribeRoute
  UpgradeRoute: typeof UpgradeRoute
  VerifyRoute: typeof VerifyRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WalletRoute: typeof WalletRoute
  CSlugRoute: typeof CSlugRoute
  EditAdIdRoute: typeof EditAdIdRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  ProductIdRoute: typeof ProductIdRoute
  ProfileCenterSectionRoute: typeof ProfileCenterSectionRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiPaymentsWebhookRoute: typeof ApiPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer-protection': {
      id: '/buyer-protection'
      path: '/buyer-protection'
      fullPath: '/buyer-protection'
      preLoaderRoute: typeof BuyerProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes': {
      id: '/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof DisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-community': {
      id: '/post-community'
      path: '/post-community'
      fullPath: '/post-community'
      preLoaderRoute: typeof PostCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job': {
      id: '/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof PostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-product': {
      id: '/post-product'
      path: '/post-product'
      fullPath: '/post-product'
      preLoaderRoute: typeof PostProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$id': {
      id: '/community/$id'
      path: '/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof CommunityIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/edit-ad/$id': {
      id: '/edit-ad/$id'
      path: '/edit-ad/$id'
      fullPath: '/edit-ad/$id'
      preLoaderRoute: typeof EditAdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/learn/$courseId': {
      id: '/learn/$courseId'
      path: '/$courseId'
      fullPath: '/learn/$courseId'
      preLoaderRoute: typeof LearnCourseIdRouteImport
      parentRoute: typeof LearnRoute
    }
    '/market/categories': {
      id: '/market/categories'
      path: '/categories'
      fullPath: '/market/categories'
      preLoaderRoute: typeof MarketCategoriesRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/search': {
      id: '/market/search'
      path: '/search'
      fullPath: '/market/search'
      preLoaderRoute: typeof MarketSearchRouteImport
      parentRoute: typeof MarketRoute
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-center/$section': {
      id: '/profile-center/$section'
      path: '/profile-center/$section'
      fullPath: '/profile-center/$section'
      preLoaderRoute: typeof ProfileCenterSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/webhook': {
      id: '/api/payments/webhook'
      path: '/api/payments/webhook'
      fullPath: '/api/payments/webhook'
      preLoaderRoute: typeof ApiPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/category/$category': {
      id: '/market/category/$category'
      path: '/category/$category'
      fullPath: '/market/category/$category'
      preLoaderRoute: typeof MarketCategoryCategoryRouteImport
      parentRoute: typeof MarketRoute
    }
  }
}

interface CommunityRouteChildren {
  CommunityIdRoute: typeof CommunityIdRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityIdRoute: CommunityIdRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface LearnRouteChildren {
  LearnCourseIdRoute: typeof LearnCourseIdRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnCourseIdRoute: LearnCourseIdRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface MarketRouteChildren {
  MarketCategoriesRoute: typeof MarketCategoriesRoute
  MarketSearchRoute: typeof MarketSearchRoute
  MarketCategoryCategoryRoute: typeof MarketCategoryCategoryRoute
}

const MarketRouteChildren: MarketRouteChildren = {
  MarketCategoriesRoute: MarketCategoriesRoute,
  MarketSearchRoute: MarketSearchRoute,
  MarketCategoryCategoryRoute: MarketCategoryCategoryRoute,
}

const MarketRouteWithChildren =
  MarketRoute._addFileChildren(MarketRouteChildren)

interface MessagesRouteChildren {
  MessagesIdRoute: typeof MessagesIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesIdRoute: MessagesIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface SettingsRouteChildren {
  SettingsSectionRoute: typeof SettingsSectionRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSectionRoute: SettingsSectionRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BuyerProtectionRoute: BuyerProtectionRoute,
  CommunityRoute: CommunityRouteWithChildren,
  CompanyRoute: CompanyRoute,
  DisputesRoute: DisputesRoute,
  EditProfileRoute: EditProfileRoute,
  FaqRoute: FaqRoute,
  FleetRoute: FleetRoute,
  InventoryRoute: InventoryRoute,
  JobsRoute: JobsRouteWithChildren,
  LearnRoute: LearnRouteWithChildren,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRouteWithChildren,
  MessagesRoute: MessagesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  PlansRoute: PlansRoute,
  PostRoute: PostRoute,
  PostCommunityRoute: PostCommunityRoute,
  PostJobRoute: PostJobRoute,
  PostProductRoute: PostProductRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaffRoute: StaffRoute,
  SubscribeRoute: SubscribeRoute,
  UpgradeRoute: UpgradeRoute,
  VerifyRoute: VerifyRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WalletRoute: WalletRoute,
  CSlugRoute: CSlugRoute,
  EditAdIdRoute: EditAdIdRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  ProductIdRoute: ProductIdRoute,
  ProfileCenterSectionRoute: ProfileCenterSectionRoute,
  UUsernameRoute: UUsernameRoute,
  ApiPaymentsWebhookRoute: ApiPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
